# Generated by Django 3.1 on 2020-09-26 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200926_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=100)),
                ('sourceproject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='projects.project')),
            ],
            options={
                'verbose_name': 'Task',
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('taskname', 'sourceproject'), name='unique taskname'),
        ),
    ]
