# Generated by Django 3.1 on 2020-09-26 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200927_0554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='unique taskname',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sourceproject',
        ),
    ]
