# Generated by Django 3.1 on 2020-09-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200927_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskdone',
            field=models.BooleanField(default=False),
        ),
    ]
