# Generated by Django 3.1.1 on 2020-09-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200927_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstudents',
            options={'verbose_name': 'Student Task'},
        ),
    ]
