# Generated by Django 3.1.1 on 2020-09-29 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20200927_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstudents',
            name='time',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
