# Generated by Django 3.1.1 on 2020-09-29 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20200930_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstudents',
            name='time',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
