# Generated by Django 3.1.1 on 2020-09-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20200930_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstudents',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
