# Generated by Django 3.1.1 on 2020-10-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20201006_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dueDate',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='dueTime',
            new_name='due_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskdone',
            new_name='task_done',
        ),
    ]
