# Generated by Django 3.1.1 on 2020-10-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20201006_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
