# Generated by Django 3.1.2 on 2020-10-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_task_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstudents',
            name='plan_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
