# Generated by Django 3.1.2 on 2020-10-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_taskstudents_plan_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstudents',
            name='plan_time',
        ),
    ]
