# Generated by Django 3.1.2 on 2020-10-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_taskstudents_plan_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstudents',
            old_name='plan_time',
            new_name='plan_percent',
        ),
    ]
